export const levelsList = [
  {
    tag: 'li',
    classList: ['levels-item'],
    textContent: '1 level',
    childTag: 'span',
    childClassList: ['levels-check'],
  },
  {
    tag: 'li',
    classList: ['levels-item'],
    textContent: '2 level',
    childTag: 'span',
    childClassList: ['levels-check'],
  },
  {
    tag: 'li',
    classList: ['levels-item'],
    textContent: '3 level',
    childTag: 'span',
    childClassList: ['levels-check'],
  },
  {
    tag: 'li',
    classList: ['levels-item'],
    textContent: '4 level',
    childTag: 'span',
    childClassList: ['levels-check'],
  },
  {
    tag: 'li',
    classList: ['levels-item'],
    textContent: '5 level',
    childTag: 'span',
    childClassList: ['levels-check'],
  },
  {
    tag: 'li',
    classList: ['levels-item'],
    textContent: '6 level',
    childTag: 'span',
    childClassList: ['levels-check'],
  },
  {
    tag: 'li',
    classList: ['levels-item'],
    textContent: '7 level',
    childTag: 'span',
    childClassList: ['levels-check'],
  },
  {
    tag: 'li',
    classList: ['levels-item'],
    textContent: '8 level',
    childTag: 'span',
    childClassList: ['levels-check'],
  },
  {
    tag: 'li',
    classList: ['levels-item'],
    textContent: '9 level',
    childTag: 'span',
    childClassList: ['levels-check'],
  },
  {
    tag: 'li',
    classList: ['levels-item'],
    textContent: '10 level',
    childTag: 'span',
    childClassList: ['levels-check'],
  },
];